---
apiVersion: v1
kind: Service
metadata:
  annotations:
    wibble: wobble
  name: tasker-svc
spec:
  #type: ClusterIP
  #type: NodePort
  type: LoadBalancer
  selector:
    app: tasker
  ports:
  - name: http
    protocol: TCP
    port: 60080
    targetPort: 80
